services:

  api:
    build:
      dockerfile: AktBob.Api/Dockerfile
      args:
        ENVIRONMENT: "development"
    ports:
      - "8080:8080"
    depends_on:
      - sql

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mhYQ%I9l*aOqYwQzCXip"