<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="aak.deskpro" Version="1.14.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AktBob.Shared\AktBob.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AktBob.Deskpro.Tests.Unit" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

</Project>
