<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="aak.deskpro" Version="1.14.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AktBob.Shared\AktBob.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AktBob.Deskpro.Tests.Unit" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

</Project>
