<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\AktBob.Database\AktBob.Database.csproj" />
      <ProjectReference Include="..\..\AktBob.Shared\AktBob.Shared.csproj" />
      <ProjectReference Include="..\..\Modules\Aktbob.Modules.Deskpro\Aktbob.Modules.Deskpro.csproj" />
      <ProjectReference Include="..\..\Modules\Aktbob.Modules.FilArkiv\Aktbob.Modules.FilArkiv.csproj" />
      <ProjectReference Include="..\..\Modules\Aktbob.Modules.Podio\Aktbob.Modules.Podio.csproj" />
    </ItemGroup>
</Project>