<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AzureFunctionsVersion>V4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AssemblyName>Aktbob.Processors.Afgørelsesskrivelse</AssemblyName>
        <RootNamespace>Aktbob.Processors.Afgørelsesskrivelse</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.2" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.2"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\AktBob.Database\AktBob.Database.csproj" />
      <ProjectReference Include="..\..\AktBob.Shared\AktBob.Shared.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>