services:
  
#  mailserver:
#    image: jijiechen/papercut:latest
#    ports:
#      - "25:25"
#      - "37408:37408"
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  
  api:
    build:
      dockerfile: AktBob.Api/Dockerfile
      args:
        ENVIRONMENT: "development"
    env_file:
      - Aktbob.Api/development.env
      - shared-configuration.dev.env
    ports:
      - "5000:8080"
    depends_on:
      - sql


  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mhYQ%I9l*aOqYwQzCXip"
      

  ###########   
  # Modules #
  ###########
  
  module-deskpro:
    build:
      dockerfile: Modules/Aktbob.Modules.Deskpro/Dockerfile
      args:
        ENVIRONMENT: "development"
        APPINSIGHTS_INSTRUMENTATIONKEY: "test"
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  
  
  module-open-orchestrator:
    build:
      dockerfile: Modules/Aktbob.Modules.OpenOrchestrator/Dockerfile
      args:
        ENVIRONMENT: "development"
        APPINSIGHTS_INSTRUMENTATIONKEY: "test"
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      
      
  module-podio:
    build:
      dockerfile: Modules/Aktbob.Modules.Podio/Dockerfile
      args:
        ENVIRONMENT: "development"
        APPINSIGHTS_INSTRUMENTATIONKEY: "test"
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"


  module-filarkiv:
    build:
      dockerfile: Modules/Aktbob.Modules.FilArkiv/Dockerfile
      args:
        ENVIRONMENT: "development"
        APPINSIGHTS_INSTRUMENTATIONKEY: "test"
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      
  ##############
  # Processors #
  ##############
  
  processor-afgoerelsesskrivelse:
    build:
      dockerfile: Processors/Aktbob.Processors.Afgoerelsesskrivelse/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.Afgoerelsesskrivelse/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
    depends_on:
      - module-deskpro
      - module-open-orchestrator
      - sql


  processor-journalize-everything:
    build:
      dockerfile: Processors/Aktbob.Processors.JournalizeEverything/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.JournalizeEverything/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
    depends_on:
      - module-deskpro
      - module-open-orchestrator
      - sql

  processor-to-filarkiv:
    build:
      dockerfile: Processors/Aktbob.Processors.ToFilArkiv/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.ToFilArkiv/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
    depends_on:
      - module-deskpro
      - module-open-orchestrator
      - module-podio
      - sql
        
  processor-to-sharepoint:
    build:
      dockerfile: Processors/Aktbob.Processors.ToSharepoint/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.ToSharepoint/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
    depends_on:
      - module-deskpro
      - module-open-orchestrator
      - module-podio
      - sql
  
  processor-document-list:
    build:
      dockerfile: Processors/Aktbob.Processors.DocumentList/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.DocumentList/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
    depends_on:
      - module-deskpro
      - module-open-orchestrator
      - module-podio
      - sql
    
  processor-os2forms-submissions:
    build:
      dockerfile: Processors/Aktbob.Processors.OS2FormsSubmissions/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.OS2FormsSubmissions/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
    depends_on:
      - sql
      - azurite
      - module-deskpro
  
  processor-cleanup:
    build:
      dockerfile: Processors/Aktbob.Processors.Cleanup/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.Cleanup/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
    depends_on:
      - sql
      - module-deskpro
      - module-open-orchestrator
  
  processor-check-ocr-screening:
    build:
      dockerfile: Processors/Aktbob.Processors.CheckOcrScreeningStatus/Dockerfile
    env_file:
      - Processors/Aktbob.Processors.CheckOcrScreeningStatus/development.env
      - shared-configuration.dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
    depends_on:
      - sql
      - module-deskpro
      - module-filarkiv
      - module-podio